<?php
/**
 * Custom defines for static keyword
 */
$_l = array();
array_push($_l, array('project_title' => 'SuperMarket | Dashboard')) ;
array_push($_l, array('Home' => 'Home')) ;
array_push($_l, array('Dashboard' => 'Dashboard')) ;
array_push($_l, array('Search' => 'Buscar...')) ;
array_push($_l, array('Product' => 'Producto')) ;
array_push($_l, array('See_product' => 'Ver Producto')) ;
array_push($_l, array('Create_Product' => 'Crear Producto')) ;
array_push($_l, array('Organization_commercial' => 'Organización Comercial')) ;
array_push($_l, array('Classify_Product' => 'Classificar Producto')) ;
array_push($_l, array('Product_Suppliers' => 'Proveedores del Producto')) ;
array_push($_l, array('Price_Managment' => 'Gestión de Precio')) ;
array_push($_l, array('Product_Taxes' => 'Impuestos del Producto')) ;
array_push($_l, array('Product_Classification' => 'Clasificación del Producto')) ;
array_push($_l, array('Search_Product' => 'Buscar Producto')) ;
array_push($_l, array('Product_Code' => 'Código de Producto')) ;
array_push($_l, array('Product_Name' => 'Nombre del Producto')) ;
array_push($_l, array('Search_button' => 'Buscar')) ;
array_push($_l, array('Classification' => 'Clasificación')) ;
array_push($_l, array('Division' => 'División')) ;
array_push($_l, array('Department' => 'Departamento')) ;
array_push($_l, array('Sub_Department' => 'Sub-Departamento')) ;
array_push($_l, array('Class_table' => 'Clase')) ;
array_push($_l, array('Sub_Class' => 'Sub-Clase')) ;
array_push($_l, array('Change' => 'Cambio')) ;
array_push($_l, array('Save' => 'Salvar')) ;
array_push($_l, array('Cancel' => 'Cancelar')) ;
array_push($_l, array('Product_Details' => 'Detalles de Producto')) ;
array_push($_l, array('List_of_Results' => 'Lista de Resultados')) ;
array_push($_l, array('Details' => 'Detalles')) ;
array_push($_l, array('Produt_Detail' => 'Detalles de Producto')) ;
array_push($_l, array('Status' => 'Estado:')) ;
array_push($_l, array('Sell_Measure' => 'Medida de Venta')) ;
array_push($_l, array('Sell_Unity' => 'Unidad de Venta')) ;
array_push($_l, array('Unity' => 'Unidad')) ;
array_push($_l, array('Net_Price' => 'Precio Neto')) ;
array_push($_l, array('Total_Dscto' => 'Total Dscto %')) ;
array_push($_l, array('Freight_Price' => 'Precio de Flete')) ;
array_push($_l, array('Total_Tax' => 'Total Impuestos %')) ;
array_push($_l, array('Purchase_Price' => 'Precio de Compra')) ;
array_push($_l, array('Branch_Name' => 'Nombre de la Sucursal')) ;
array_push($_l, array('Retail_Price' => 'Precio al Por Menor')) ;
array_push($_l, array('Retail_Margin' => 'Margen Minorista')) ;
array_push($_l, array('Wholesale_Price' => 'Precio al Por Mayor')) ;
array_push($_l, array('Wholesale_Margin' => 'Margen Mayorista')) ;
array_push($_l, array('Main_Provider' => 'Proveedor Principal')) ;
array_push($_l, array('Provider' => 'Proveedor')) ;
array_push($_l, array('Rut_Provider' => 'Rut. Proveedor')) ;
array_push($_l, array('Provider_name' => 'Nombre del Proveedor')) ;
array_push($_l, array('Product_Creation' => 'Creación de Producto')) ;
array_push($_l, array('Product_Bar_Code' => 'Código de Barras del Producto')) ;
array_push($_l, array('Generate_Code' => 'Generar Codigo')) ;
array_push($_l, array('Product_Unity' => 'Unidad de Producto')) ;
array_push($_l, array('Measure_Unity' => 'Unidad de Medida')) ;
array_push($_l, array('Provider_Price' => 'Precio del Proveedor')) ;
array_push($_l, array('Dscto_1' => '% Dscto 1')) ;
array_push($_l, array('Dscto_2' => '% Dscto 2')) ;
array_push($_l, array('Dscto_3' => '% Dscto 3')) ;
array_push($_l, array('Dscto_4' => '% Dscto 4')) ;
array_push($_l, array('Sub_Price' => 'Sub Precio')) ;
array_push($_l, array('Price_Without_Tax' => 'Precio sin Impuestos')) ;
array_push($_l, array('Taxes_List' => 'Lista de Impuestos')) ;
array_push($_l, array('Select_Tax' => 'Seleccionar Impuesto')) ;
array_push($_l, array('New_Tax' => 'Nuevo Impuesto')) ;
array_push($_l, array('Sell_Price' => 'Precio de Venta')) ;
array_push($_l, array('Product_Provider' => 'Proveedor de Productos')) ;
array_push($_l, array('Provider_RUT' => 'RUT del Proveedor')) ;
array_push($_l, array('Create_Poduct' => 'Crear Producto')) ;
array_push($_l, array('LIVE_URL_BASE' => 'http://164.77.122.66:85/')) ;
array_push($_l, array('ProductsAPIv2' => 'ProductsAPIv2/index.php/API/')) ;
array_push($_l, array('TaxAPI' => 'TaxAPI/index.php/API/')) ;
array_push($_l, array('ProviderAPI' => 'ProviderAPI/index.php/API/')) ;
array_push($_l, array('getProductDetailsbyID' => 'v1/Products/getProductDetailsbyID')) ;
array_push($_l, array('getProductsbyName' => 'v1/Products/getProductsbyName')) ;
array_push($_l, array('getAllProductsUnity' => 'v1/ProductUnity/getAllProductsUnity')) ;
array_push($_l, array('getAllTaxes' => 'v1/Taxes/getAllTaxes')) ;
array_push($_l, array('getAllDivision' => 'v1/ProductsClassification/getAllDivision')) ;
array_push($_l, array('getAllDepartmentsByCodeDivision' => 'v1/ProductsClassification/getAllDepartmentsByCodeDivision')) ;
array_push($_l, array('getAllSubDepartmentsByCodeDepartment' => 'v1/ProductsClassification/getAllSubDepartmentsByCodeDepartment')) ;
array_push($_l, array('getAllClassBySubDepartment' => 'v1/ProductsClassification/getAllClassBySubDepartment')) ;
array_push($_l, array('getAllSubClassByClass' => 'v1/ProductsClassification/getAllSubClassByClass')) ;
array_push($_l, array('getSuppliersbyName' => 'v1/Suppliers/getSuppliersbyName')) ;
array_push($_l, array('getSuppliersbyID' => 'v1/Suppliers/getSuppliersbyID')) ;
$text = 'here';
function l($key){
//print_r($_l);exit;
	//global $text;
	return $text;
}